name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install mpfr
      run: sudo apt-get install gcc-10 libmpfr-dev libmpc-dev

    - name: Build libgccjit
      run: |
        cd ..
        ls
        mkdir build install
        cd build
        ../gcc/configure --enable-host-shared --enable-languages=c,jit,lto --disable-bootstrap --disable-multilib --prefix=$(pwd)/../install/usr --libdir=$(pwd)/../install/usr/lib --libexecdir=$(pwd)/../install/usr/lib
        make -j4
        make install

    - name: Build Debian package
      run: |
        cd ..
        mkdir install/DEBIAN
        cat > install/DEBIAN/control << EOF
        Package: gcc-13
        Version: 13
        Architecture: amd64
        Maintainer: Antoni Boucher <bouanto@zoho.com>
        Description: gcc 13 for rustc_codegen_gcc CI
        EOF
        dpkg-deb --root-owner-group --build install
        mv install.deb gcc-13.deb

    - uses: actions/upload-artifact@v3
      with:
        name: gcc-13
        path: /home/runner/work/gcc/gcc-13.deb
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      with:
          name: libgccjit.so
          path: |
            /home/runner/work/gcc/build/gcc/libgccjit.so
            /home/runner/work/gcc/build/gcc/lto1
            /home/runner/work/gcc/build/gcc/liblto_plugin.so
            /home/runner/work/gcc/build/gcc/lto-wrapper
            /home/runner/work/gcc/build/gcc/crtbeginS.o
            /home/runner/work/gcc/build/gcc/crtendS.o
